### ISSUE TITLE
Flutter Web AssetNotFoundException

### ISSUE THREAD

**Issue by mkiisoft** [leisim/hive#12]
While trying to import the library, I'm getting the following errors:

```
[WARNING]build_web_compilers:entrypoint on web/main.dart: Unable to read hive|lib/hive.ddc.js, check your console or the `.dart_tool/build/generated/hive/lib/hive.ddc.js.errors` log file.
[SEVERE]build_web_compilers:entrypoint on web/main.dart: AssetNotFoundException: hive|lib/hive.ddc.js
```

**Comment by leisim** [comment]
What does the `hive.ddc.js.errors` log file say?

**Comment by mkiisoft** [comment]
@leisim I wasn't aware of a log, let me try to install it again and check the logs (I'll update this response)

**Comment by leisim** [comment]
Thanks!

**Comment by mkiisoft** [comment]
Done, apparently is an URI issue.

**Comment by leisim** [comment]
This is strange... I don't manage to reproduce the error. Could you explain me how you get this error?

**Comment by mkiisoft** [comment]
I'm using Flutter Web:

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
[!] Connected device

Flutter 1.7.8+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 20e59316b8 (3 weeks ago) • 2019-07-18 20:04:33 -0700
Engine • revision fee001c93f
Tools • Dart 2.4.0
```
This is my .yaml

```
environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any
  firebase: any
  service_worker: ^0.2.3
  hive: ^0.3.0+1

dev_dependencies:
  build_runner: ^1.6.5
  build_web_compilers: '>=1.0.0 <2.0.0'
  pedantic: ^1.8.0+1

flutter:
  uses-material-design: true

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
```

All I did was adding:

`import 'package:hive/hive.dart';`

tried to compile the code and I got that error when using: webdev serve
